Authentification with EPFL people API
The-Software-Enterprise/assos pull request #10
Opened 2024-04-08 08:27 UTC by Tikipiou

2024-04-11 15:26 UTC, Reza-rgb requested changes
Overall this is a great PR ! There are just some minor changes : delete debugging log, commented code and comply with previous code style / implementation

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/MainActivity.kt
> +      // FirebaseFirestore.getInstance().firestoreSettings = firestoreSettings
Delete the commented code

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/model/data/User.kt
> +    val firsname: String,
Typo: `firsname` should be replaced by `firstName`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/model/data/User.kt
Consider using CamelCase convention: replace `lastname` by `lastName`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/model/service/impl/AuthServiceImpl.kt
> +  // val ok = auth.useEmulator("10.0.2.2",9099)
Delete commented code

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/model/service/impl/AuthServiceImpl.kt
> +  // TODO: if you are using the firestore emulator, make sure to change the host and port to match
The keyword TODO is maybe not the best in this context, it is more an advice for future implementations. You could replace it by `NB`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/model/view/LoginViewModel.kt
> +  // fun goToSignIn() = navController.navigate("Login")
Remove commented code

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/LoginScreen.kt
> +fun LoginScreen(navController: NavHostController) {
replace `navController` by an argument with type `NavigationActions`. It is better for encapsulation (we limit the access to the NavHostController)

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/LoginScreen.kt
> +            // if clikecd, go to sign up page using hilt navigation
Typo: `clikecd` should become `clicked`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +fun SignUpScreen(navController: NavController) {
Same remark: consider using NavigationsActions

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +        modifier = Modifier.semantics { testTag = "password" })
We use a different way to write testTags in the rest of the project, it is maybe a good idea to write it in the same way in the entire project. `Modifier.semantics { testTag = "password" }` would become `Modifier.testTag("password")`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +        modifier = Modifier.semantics { testTag = "confirmPassword" })
Same remark:  `Modifier.semantics { testTag = "confirmPassword" }` would become `Modifier.testTag("confirmPassword")`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +            println(loginViewModel.firestoreInstance)
Delete debugging log

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +            // Firebase.functions.useEmulator("10.0.2.2", 5001)
Delete commented code

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +        modifier = Modifier.semantics { testTag = "signUpB" }) {
Same remark:  `Modifier.semantics { testTag = "signUpB" }` would become `Modifier.testTag("signUpB")`

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +                  println(result)
Not sure if it is a debugging log

2024-04-11 15:26 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +                  println(it.message)
Not sure if it is a debugging log

2024-04-11 15:26 UTC, Reza-rgb commented on functions/main.py
> +    print(req)
Delete debugging log

2024-04-11 15:26 UTC, Reza-rgb commented on functions/main.py
> +        print(profile[0])
Delete debugging log

2024-04-11 15:26 UTC, Reza-rgb commented on functions/main.py
> +        print("User added to firestore")
Not sure if it is debugging log

2024-04-12 07:00 UTC, Reza-rgb approved these changes
All the highlighted problems were resolved. Perfect !

2024-04-12 07:10 UTC, marinPh commented
corrected the formatting code

2024-04-12 08:35 UTC, Reza-rgb approved these changes
Formatting was applied, great !

2024-04-12 08:40 UTC, merged