Ticket system Frontend
The-Software-Enterprise/assos pull request #143
Opened 2024-05-07 13:38 UTC by alicepotter

## Context
In this PR, I implemented the front end of the ticket system pages.

## What's New
- Added a ticket icon in the bottom bar navigation.
- Ticket: A data class representing a ticket.
- MyTickets.kt: A screen that displays the user's tickets.
- ScanTicket.kt: A screen that will be used to scan tickets.
- TicketDetails.kt: A screen showing the details of a ticket.

## What's to Come
The backend for the ticket system will be implemented in a PR coming shortly. For now, manual testing of the navigation has been done. Once the backend is completed, tests will be added.

## Demo

https://github.com/The-Software-Enterprise/assos/assets/91310864/acb8a1c4-2606-4dd8-9dca-997cb8598978

2024-05-07 14:03 UTC, JulesHerrscher requested changes
nice changes to start the implementation of the tickets, but database changes are mandatory as well as tests.

2024-05-07 14:03 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/model/data/Ticket.kt
the ticket class requires only an id and an eventid and maybe a userId.

2024-05-09 16:03 UTC, Julio12344 requested changes

2024-05-09 16:03 UTC, Julio12344 commented on app/src/main/java/com/swent/assos/ui/screens/ticket/TicketDetails.kt
> +              modifier = Modifier.padding(8.dp).testTag("Description"))
For the text use the Typography Theme.

2024-05-10 13:19 UTC, Julio12344 approved these changes

2024-05-10 13:45 UTC, JulesHerrscher approved these changes
Nice changes, it satisfies all the requirements to get merged.

2024-05-10 13:45 UTC, JulesHerrscher commented on app/src/androidTest/java/com/swent/assos/MyTicketsTest.kt
nice to already have tests !

2024-05-10 13:45 UTC, JulesHerrscher commented on app/src/androidTest/java/com/swent/assos/ScanTicketTest.kt
same here, nice to have tests for the scan tickets, good practice to directly fill the datacache to "mock" the database.

2024-05-10 13:45 UTC, JulesHerrscher commented on app/src/androidTest/java/com/swent/assos/TicketDetailsTest.kt
There is just some commented code.

2024-05-10 13:45 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/model/data/Ticket.kt
Nice changes !

2024-05-10 13:45 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/model/view/TicketViewModel.kt
clean viewModel. Sonarcloud indicates that the dispatchers are useless when used with only suspending functions.

2024-05-11 10:01 UTC, merged