Color setup and logo setup
The-Software-Enterprise/assos pull request #25
Opened 2024-04-11 16:48 UTC by MaximilienG1

I've set up the exact colors we'll need to use in the application, i.e. the colors for the background, the buttons and the text in these different colors.  
I've also set up the svg logos for the different pages of our application, for greater clarity.

2024-04-11 17:33 UTC, JulesHerrscher requested changes
Good pull request, it is needed to discuss about the name of the application in the settings file

2024-04-11 17:33 UTC, JulesHerrscher commented on settings.gradle.kts
The project name is still Assos in my project, we should pay attention to this change

2024-04-11 17:33 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/ui/screens/Profil.kt
the expermental3Api seems to not be mandatory for such a small composable.

2024-04-11 18:20 UTC, Reza-rgb requested changes
It will be very handy to have all these pretty colours, thanks ! The different logos look good also ! I just highlighted a few minor adjustment about the general organisation. As Jules said, you also need to format the new code so that you pass the CI and we can merge with the main branch

2024-04-12 12:08 UTC, Tikipiou commented on settings.gradle.kts
It should not be a problem

2024-04-12 12:16 UTC, closed without merging