Login signup testing
The-Software-Enterprise/assos pull request #38
Opened 2024-04-12 21:17 UTC by marinPh

A pull request that tests and enables out of Emulator testing for functions and other features, now the app knows if we are using an emulator automatically

2024-04-16 15:07 UTC, JulesHerrscher reviewed
Nice PR, we will be able to use the emulator in order to perform tests. Some little changes could be made.

2024-04-16 15:08 UTC, Reza-rgb requested changes
This is a very cool tool ! I just highlighted a few security adjustments (addresses and port numbers directly available in code) and some strange code (thread started then directly joined)

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/config/Config.kt
> +      val url = URL("http://10.0.2.2:4400/emulators")
Same comment here, [String Resource](https://developer.android.com/guide/topics/resources/string-resource) can be a good idea for the address `10.0.2.2:4400`

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/MainActivity.kt
> +      FirebaseAuth.getInstance().useEmulator("10.0.2.2", 9099)
Same comment here, [String Resource](https://developer.android.com/guide/topics/resources/string-resource) can be a good idea for the address `10.0.2.2`

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/config/Config.kt
> +    thread.join()
Code smells, there is surely a better way to deal with this thread (just run a code rather than wrap it in a thread)

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/config/Config.kt
> +      thread1.join()
Code smells, there is surely a better way to deal with this thread (just run a code rather than wrap it in a thread)

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/config/Config.kt
> +    return checkFirebaseEmulator("10.0.2.2", "9099")
Same comment here, [String Resource](https://developer.android.com/guide/topics/resources/string-resource) can be a good idea for the address `10.0.2.2` and port `9099`

2024-04-16 15:08 UTC, Reza-rgb commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
> +              functions.useEmulator("10.0.2.2", 5001)
Same comment here, [String Resource](https://developer.android.com/guide/topics/resources/string-resource) can be a good idea for the address `10.0.2.2` and port `5001`

2024-04-17 16:09 UTC, Tikipiou requested changes
Very good job!

2024-04-17 16:09 UTC, Tikipiou commented on app/src/main/java/com/swent/assos/model/data/User.kt
> +    var associations: List<Triple<String, String, Int>>,
It was better before because we only store the IDs of the Association in the User, not all the information

2024-04-17 16:09 UTC, Tikipiou commented on emulatorFiles/.emulator-data/firestore_export/all_namespaces/kind_associations/output-0
Is it automatically generated by the emulator ? If yes, we don't need it on git

2024-04-17 16:09 UTC, Tikipiou commented on emulatorFiles/.emulator-data/firestore_export/firestore_export.overall_export_metadata
Is it automatically generated by the emulator ? If yes, we don't need it on git

2024-04-17 18:37 UTC, marinPh commented on emulatorFiles/.emulator-data/firestore_export/firestore_export.overall_export_metadata
no it generated by a command to export global firestore collections

2024-04-17 18:38 UTC, marinPh commented on app/src/main/java/com/swent/assos/MainActivity.kt
> +  }
we can now changing this you are right

2024-04-18 09:56 UTC, marinPh commented on .github/workflows/ci.yml
> -          firebase emulators:exec --only functions "./gradlew check --parallel --build-cache"
auth is very important aswell for login and signup tests as we want to check if we added a new user, and mostly 1 account per email is permitted

2024-04-18 10:16 UTC, marinPh commented on emulatorFiles/.emulator-data/firestore_export/all_namespaces/kind_associations/output-0
signupScreen.child

2024-04-18 11:31 UTC, JulesHerrscher approved these changes
Really good PR, I noticed only minor changes.

2024-04-18 11:31 UTC, JulesHerrscher commented on .github/workflows/ci.yml
> +          firebase emulators:exec "./gradlew check --parallel --build-cache"
does the check command not require the import from the database ?

2024-04-18 11:31 UTC, JulesHerrscher commented on app/src/androidTest/java/com/swent/assos/OverviewTest.kt
> +    verify { mockNavActions.navigateTo("AssociationPage/jMWo6NgngIS2hCq054TF") }
maybe use a variable to store the id of the association

2024-04-18 11:31 UTC, JulesHerrscher commented on app/src/androidTest/java/com/swent/assos/SignupTest.kt
> +        step("Open Signup Screen") {
what is the signup button in the sign up screen ? Why do we verify that it navigates to the sign up if we are already in that screen, maybe a liitle typo.

2024-04-18 11:31 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/MainActivity.kt
> +    if (firestoreEmu) {
you can merge this if with the nested if, not really a required change.

2024-04-18 11:31 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/config/Config.kt
> +    return withContext(Dispatchers.IO) {
avoid hardcoded dispatchers, I managed to inject a dispatcher in another class but we should discuss about wether it is really needed or not

2024-04-18 11:31 UTC, JulesHerrscher commented on app/src/main/java/com/swent/assos/ui/login/SignUpScreen.kt
>                  .addOnSuccessListener { task ->
you can use _ instead of task because you are not using the task in this lamda, not really needed to change.

2024-04-18 12:15 UTC, Tikipiou approved these changes

2024-04-18 12:34 UTC, Reza-rgb approved these changes
All good !

2024-04-18 12:35 UTC, merged