Signup login implementation
The-Software-Enterprise/assos pull request #60
Opened 2024-04-18 21:10 UTC by marinPh

New error and crash prevention in Signing up

2024-04-19 11:14 UTC, Tikipiou requested changes
Overall, this is good work.

2024-04-19 11:14 UTC, Tikipiou commented on app/src/main/java/com/swent/assos/MainActivity.kt
Move this in `Config.kt`.

2024-04-19 11:14 UTC, Tikipiou commented on app/src/main/java/com/swent/assos/model/view/LoginViewModel.kt
It's better to have two callbacks : `onSuccess` and `onError`

2024-04-19 12:01 UTC, marinPh commented on app/src/main/java/com/swent/assos/model/view/LoginViewModel.kt
Would influence behaviour of the tests

2024-04-20 17:30 UTC, Tikipiou approved these changes
Very good job !

2024-04-20 17:30 UTC, merged